name: CI/CD Pipeline - Test, Build, Deploy

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.FIREBASE_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - run: npm install
      - run: npm run build
      - run: npm test

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/movie-list
          TAG=${GITHUB_SHA::7}

          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG

          docker tag $IMAGE:$TAG $IMAGE:latest
          docker push $IMAGE:latest

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        run: |
          REGION=asia-southeast2
          SERVICE_NAME=seenit-coba
          IMAGE=docker.io/${{ secrets.DOCKER_USERNAME }}/movie-list:latest

          gcloud run deploy $SERVICE_NAME \
            --image=$IMAGE \
            --platform=managed \
            --region=$REGION \
            --allow-unauthenticated