name: CI/CD Pipeline - Test, Build, Deploy

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout source code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Setup Node.js untuk testing
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    # 3. Install dependencies dan test
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    # 4. Login ke Docker Hub
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 5. Build dan push Docker image ke Docker Hub
    - name: Build and Push Docker Image
      run: |
        IMAGE=gabriellajp/my-app
        TAG=${GITHUB_SHA::7}

        docker build -t $IMAGE:$TAG .
        docker push $IMAGE:$TAG

        docker tag $IMAGE:$TAG $IMAGE:latest
        docker push $IMAGE:latest

    # 6. Authenticate ke Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.secrets.GCP_CREDENTIALS }}

    # 7. Setup Google Cloud SDK
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    # 8. Deploy ke Google Cloud Run
    - name: Deploy to Cloud Run
      run: |
        REGION=asia-southeast2
        SERVICE_NAME=seenit-coba
        IMAGE=docker.io/gabriellajp/my-app:latest

        gcloud run deploy $SERVICE_NAME \
          --image=$IMAGE \
          --platform=managed \
          --region=$REGION \
          --allow-unauthenticated