name: Build and Push Docker Image

on:
    push:
        branches:
            - main # atau branch lain seperti "dev"

jobs:
    docker:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Build and push Docker image
              run: |
                  IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/my-app
                  TAG=${GITHUB_SHA}

                  docker build -t $IMAGE_NAME:$TAG .
                  docker push $IMAGE_NAME:$TAG

                  docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
                  docker push $IMAGE_NAME:latest